#!/usr/bin/env bash
# Transfer file from client to server
# Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY

if [ $# -eq 4 ]; then
	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
