#!/usr/bin/env bash
# install nginx
# add dir and new index html file
# rewrite config file
# reload nginx

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

mkdir -p /var/www/holberton
echo "Holberton School" > /var/www/holberton/holberton.html

echo "http {
	server {
		listen 80;
		server_name amacharla.space;

		root /var/www/holberton;
		index holberton.html;

		rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
}
events {
}" > /etc/nginx/nginx.conf

nginx -s reload
