#!/usr/bin/env bash
# install nginx
# add custom dir and error file
# rewrite config file
# reload nginx service

sudo apt-get -y update
sudo apt-get -y install nginx
sudo service nginx start

mkdir -p /var/www/holberton
echo "Ceci n'est pas une page" > /var/www/holberton/custom_error.html

echo "http {
	server {
		listen 80;

		root /var/www/holberton;
		index holberton.html;

		rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;

		error_page 404 /custom_error.html;

		location /custom_error.html{
			internal;
		}
	}
}
events {
}" > /etc/nginx/nginx.conf

nginx -s reload
