#!/usr/bin/env bash

mkdir -p /var/www/holberton
echo "Ceci n'est pas une page" > /var/www/holberton/custom_error.html

echo "http {
	server {
		listen 80 default_server;
		listen [::]:80 default_server ipv6only=on;

		root /var/www/holberton;
		index holberton.html;

		rewrite ^/redirect_me$ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;

		error_page 404 /custom_error.html;

		location /custom_error.html{
			root /var/www/holberton;
			internal;
		}
	}
}
events {
}" > /etc/nginx/nginx.conf

nginx -s reload
