#!/usr/bin/env bash
#Display information about subdomains

if [ "$1" ]; then
	if [ "$2" ]; then
		dig "$1.$2" +noall +answer | awk -v arg="$1" '{print "This subdomain " arg " is a " $4 " record and points to " $5}' | tail -1 
	else
		dig "www.$1" +noall +answer | awk '{print "This subdomain www is a " $4 " record and points to " $5}' | tail -1 
		dig "lb-01.$1" +noall +answer | awk '{print "This subdomain lb-01 is a " $4 " record and points to " $5}' | tail -1 
		dig "web-01.$1" +noall +answer | awk '{print "This subdomain web-01 is a " $4 " record and points to " $5}' | tail -1 
		dig "web-02.$1" +noall +answer | awk '{print "This subdomain web-02 is a " $4 " record and points to " $5}' | tail -1 
	fi
else
	echo "Must Pass a Domain Name"
fi
