#!/usr/bin/env bash
# reassigns to port 80 and get rid of ipv6
service nginx stop
sed -ri 's/listen [0-9]+ default_server/listen 80 default_server/g' /etc/nginx/sites-enabled/default
sed -ri '/ipv6only=on/d' /etc/nginx/sites-enabled/default
