#!/usr/bin/env bash
# changes local host ipaddress and adds facebook
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '2 i\8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
