#!/usr/bin/env bash
# Changing settings to have nginx run under user nginx
pkill apache2
chown nginx:nginx /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sed -i 's/listen 80/listen 8080/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx restart
